feat: update to use nvf

diff --git a/bin/sb b/bin/sb
--- a/bin/sb
+++ b/bin/sb
@@ -5,14 +5,36 @@
 # Takes endpoint as an argument
 # Example: sb /event/<event_id>
 
-endpoint=$1
+api_call() {
+  xh https://skybox.vividseats.com/services$1 \
+    X-Api-Token:$SB_API_TOKEN \
+    X-Application-Token:$SB_APP_TOKEN \
+    Accept:application/json \
+    Cache-Control:no-cache \
+    Accept-Encoding:application/json \
+    Content-Type:application/json \
+    X-Account:$SB_ACCOUNT
+}
 
-xh https://skybox.vividseats.com/services$endpoint \
-  X-Api-Token:$SB_API_TOKEN \
-  X-Application-Token:$SB_APP_TOKEN \
-  Accept:application/json \
-  Cache-Control:no-cache \
-  Accept-Encoding:application/json \
-  Content-Type:application/json \
-  X-Account:$SB_ACCOUNT | vimf json
+OPTSTRING=":p"
 
+plain=0
+
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    p)
+      plain=1
+      shift;;
+    ?)
+      echo "Invalid option: -${OPTARG}"
+      exit 1
+      ;;
+  esac
+done
+
+if [[ plain -eq 0 ]];
+then
+  api_call $1 | nvf json
+else
+  api_call $1
+fi
diff --git a/bin/tn b/bin/tn
--- a/bin/tn
+++ b/bin/tn
@@ -5,9 +5,39 @@
 # Takes endpoint as an argument
 # Example: tn /event/venue/<event_id>
 
-endpoint=$1
+api_call() {
+				xh https://www.tn-apis.com/event/v4$1 \
+								"Authorization:$TN_API_TOKEN" \
+								"Accept: application/json" \
+								"X-Identity-Context: $TN_IDENTITY"
+}
 
-xh https://www.tn-apis.com/event/v4$endpoint \
-  "Authorization:$TN_API_TOKEN" \
-  "Accept: application/json" \
-  "X-Identity-Context: $TN_IDENTITY" | vimf json
+OPTSTRING=":hp"
+
+plain=0
+
+while getopts ${OPTSTRING} opt; do
+  case ${opt} in
+    p)
+      plain=1
+      shift;;
+    h)
+      printf "Usage tn [-p for plain] <endpoint>\n\n"
+      printf "Endpoints:\n"
+      printf "\t- /events/events\n"
+      printf "\t- /events/venues\n"
+      exit 0
+      ;;
+    ?)
+      echo "Invalid option: -${OPTARG}"
+      exit 1
+      ;;
+  esac
+done
+
+if [[ plain -eq 0 ]];
+then
+  api_call $1 | nvf json
+else
+  api_call $1
+fi
